### ISSUE TITLE
Error in code list encodings?

### ISSUE THREAD

**Issue by heidivanparys** [ISO-TC211/GOM#11]
When executing the following query on https://def.isotc211.org/ontologies/iso19115/-1/2018/CitationAndResponsiblePartyInformation.rdf using [ARQ](https://jena.apache.org/documentation/query/cmds.html)

```
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix dct: <http://purl.org/dc/terms/>
prefix dctype: <http://purl.org/dc/dcmitype/>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix prov: <http://www.w3.org/ns/prov#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sdo: <http://schema.org/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix vcard: <http://www.w3.org/2006/vcard/ns#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix iso19150-2: <http://def.isotc211.org/iso19150/-2/2012/base#>
prefix iso19115-1_445: <http://def.isotc211.org/iso19115/-1/2014/CommonClasses#>
prefix iso19115-1_455: <http://def.isotc211.org/iso19115/-1/2014/ExtentInformation#>
prefix iso19115-1: <http://def.isotc211.org/iso19115/-1/2018/CitationAndResponsiblePartyInformation#>
prefix iso19115-1Code: <http://def.isotc211.org/iso19115/-1/2018/CitationAndResponsiblePartyInformation/code/>

SELECT ?prefLabel ?definition
WHERE {
	?concept skos:prefLabel ?prefLabel;
		     skos:definition ?definition;
		     skos:inScheme <http://def.isotc211.org/iso19115/-1/2018/CitationAndResponsiblePartyInformation/code/CI_RoleCode>.
}
ORDER BY ?prefLabel
```

`arq.bat --data=https://def.isotc211.org/ontologies/iso19115/-1/2018/CitationAndResponsiblePartyInformation.rdf --results=CSV --file="C:\path\to\file\containing\query" > "C:\path\to\output\as\csv"`

I get the following error:

```
ERROR riot                 :: [line: 1298, col: 78] {E201} rdf:resource not allowed as attribute here.
Failed to load data
```

When using a copy of CitationAndResponsiblePartyInformation.rdf in which all occurrences of `<skos:Concept rdf:resource are` changed to `<skos:Concept rdf:about` , the query is executed fine and I get the result I expect. I am not sure though, that that RDF actually is correct according to the SKOS spec, but at least I don't get an error.

I cannot find a description of `skos:members` in https://www.w3.org/TR/skos-reference/#collections , I can can only find `skos:member` and `skos:memberList`. Should the SKOS Collections be encoded in a slightly different way in order to conform to the spec?

**Comment by BrodeurJS** [comment]
Thanks for reporting this error! The UML2OWL generator has been fixed for its future use. https://def.isotc211.org/ontologies/iso19115/-1/2018/CitationAndResponsiblePartyInformation.rdf ontology and others have also been corrected. There are still ontologies that need to be checked to ensure their validity. This will be done shortly.
