### ISSUE TITLE
Conflicting URI for 19150-2 base

### ISSUE THREAD

**Issue by dr-shorthair** [ISO-TC211/GOM#2]
The Ontology URI for the 19150-2 base ontology is 
   http://def.isotc211.org/iso19150-2/2012/base
and the corresponding namespace for components is 
  http://def.isotc211.org/iso19150-2/2012/base#
- see https://raw.githubusercontent.com/ISO-TC211/GOM/master/isotc211_GOM_harmonizedOntology/19150-2/2012/base.owl 

However, the importing ontologies use 
  http://def.isotc211.org/iso19150/-2/2012/base 

note the extra "/" before the "-2" 

THis is causing errors in processing. 
Which is correct? And can you fix it please!

**Comment by BrodeurJS** [comment]
Good catch Simon,

It was in iso19150-2 base ontology that a "/" was missing. It is now fixed. Let me know if it fine on your side.
